//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11thLauncher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_11thLauncher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon presets.
        /// </summary>
        public static string S_ADDON_PRESETS {
            get {
                return ResourceManager.GetString("S_ADDON_PRESETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About 11th MEU Launcher.
        /// </summary>
        public static string S_APP_ABOUT {
            get {
                return ResourceManager.GetString("S_APP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11th MEU Launcher.
        /// </summary>
        public static string S_APP_NAME {
            get {
                return ResourceManager.GetString("S_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11th MEU Launcher Settings.
        /// </summary>
        public static string S_APP_SETTINGS {
            get {
                return ResourceManager.GetString("S_APP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string S_BTN_ABOUT {
            get {
                return ResourceManager.GetString("S_BTN_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the launcher.
        /// </summary>
        public static string S_BTN_ABOUT_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ABOUT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected item down.
        /// </summary>
        public static string S_BTN_ADDONS_DOWN_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ADDONS_DOWN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected item up.
        /// </summary>
        public static string S_BTN_ADDONS_UP_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ADDONS_UP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string S_BTN_SETTINGS {
            get {
                return ResourceManager.GetString("S_BTN_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings window.
        /// </summary>
        public static string S_BTN_SETTINGS_TIP {
            get {
                return ResourceManager.GetString("S_BTN_SETTINGS_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string S_DEFAULT_PROFILE_NAME {
            get {
                return ResourceManager.GetString("S_DEFAULT_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmA 3.
        /// </summary>
        public static string S_GAME_NAME {
            get {
                return ResourceManager.GetString("S_GAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by {0}.
        /// </summary>
        public static string S_LABEL_APP_AUTHOR {
            get {
                return ResourceManager.GetString("S_LABEL_APP_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build {0} [{1}] - {2}.
        /// </summary>
        public static string S_LABEL_BUILD {
            get {
                return ResourceManager.GetString("S_LABEL_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is distributed under GNU GPL v2 license. The program uses code from the following external libraries:.
        /// </summary>
        public static string S_LABEL_LICENSE {
            get {
                return ResourceManager.GetString("S_LABEL_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join server.
        /// </summary>
        public static string S_LAUNCH_JOIN_SERVER {
            get {
                return ResourceManager.GetString("S_LAUNCH_JOIN_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ArmA 3.
        /// </summary>
        public static string S_LAUNCH_NORMAL {
            get {
                return ResourceManager.GetString("S_LAUNCH_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled domain exception.
        /// </summary>
        public static string S_MSG_GENERIC_DOMAIN_EXCEPTION {
            get {
                return ResourceManager.GetString("S_MSG_GENERIC_DOMAIN_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        public static string S_MSG_GENERIC_EXCEPTION {
            get {
                return ResourceManager.GetString("S_MSG_GENERIC_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution path has not been auto-detected, select it manually on the settings window before using the application.
        /// </summary>
        public static string S_MSG_PATH_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution path.
        /// </summary>
        public static string S_MSG_PATH_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional parameters.
        /// </summary>
        public static string S_PARAMETER_ADDITIONAL {
            get {
                return ResourceManager.GetString("S_PARAMETER_ADDITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other parameters to use.
        /// </summary>
        public static string S_PARAMETER_ADDITIONAL_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_ADDITIONAL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line parameter.
        /// </summary>
        public static string S_PARAMETER_COMMAND {
            get {
                return ResourceManager.GetString("S_PARAMETER_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty world.
        /// </summary>
        public static string S_PARAMETER_EMPTY_WORLD {
            get {
                return ResourceManager.GetString("S_PARAMETER_EMPTY_WORLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t load any world by default.
        /// </summary>
        public static string S_PARAMETER_EMPTY_WORLD_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_EMPTY_WORLD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable file patching.
        /// </summary>
        public static string S_PARAMETER_FILE_PATCHING {
            get {
                return ResourceManager.GetString("S_PARAMETER_FILE_PATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows loading of unpacked data.
        /// </summary>
        public static string S_PARAMETER_FILE_PATCHING_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_FILE_PATCHING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for hugepages on memory.
        /// </summary>
        public static string S_PARAMETER_HUGE_PAGES {
            get {
                return ResourceManager.GetString("S_PARAMETER_HUGE_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables hugepages support on memory.
        /// </summary>
        public static string S_PARAMETER_HUGE_PAGES_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_HUGE_PAGES_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Hyper-Threading.
        /// </summary>
        public static string S_PARAMETER_HYPERTHREADING {
            get {
                return ResourceManager.GetString("S_PARAMETER_HYPERTHREADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the use of CPU cores with Hyper-Threading.
        /// </summary>
        public static string S_PARAMETER_HYPERTHREADING_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_HYPERTHREADING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocator - 32-bit.
        /// </summary>
        public static string S_PARAMETER_MALLOC_32 {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select memory allocator to use.
        /// </summary>
        public static string S_PARAMETER_MALLOC_32_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_32_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocator - 64-bit.
        /// </summary>
        public static string S_PARAMETER_MALLOC_64 {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select memory allocator to use.
        /// </summary>
        public static string S_PARAMETER_MALLOC_64_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_64_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System (Windows).
        /// </summary>
        public static string S_PARAMETER_MALLOC_SYSTEM {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs.
        /// </summary>
        public static string S_PARAMETER_NO_LOGS {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save errors to the RPT log.
        /// </summary>
        public static string S_PARAMETER_NO_LOGS_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_LOGS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off multicore.
        /// </summary>
        public static string S_PARAMETER_NO_MULTICORE {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_MULTICORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the use of multiple cores.
        /// </summary>
        public static string S_PARAMETER_NO_MULTICORE_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_MULTICORE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pause.
        /// </summary>
        public static string S_PARAMETER_NO_PAUSE {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to continue running the game when the window is not active.
        /// </summary>
        public static string S_PARAMETER_NO_PAUSE_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_PAUSE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable splash screens.
        /// </summary>
        public static string S_PARAMETER_NO_SPLASH {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_SPLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the splash screens on load.
        /// </summary>
        public static string S_PARAMETER_NO_SPLASH_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_SPLASH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show script errors.
        /// </summary>
        public static string S_PARAMETER_SHOW_ERRORS {
            get {
                return ResourceManager.GetString("S_PARAMETER_SHOW_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show script errors on screen.
        /// </summary>
        public static string S_PARAMETER_SHOW_ERRORS_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_SHOW_ERRORS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static screen on main menu.
        /// </summary>
        public static string S_PARAMETER_SKIP_INTRO {
            get {
                return ResourceManager.GetString("S_PARAMETER_SKIP_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the scene on the main menu.
        /// </summary>
        public static string S_PARAMETER_SKIP_INTRO_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_SKIP_INTRO_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force windowed mode.
        /// </summary>
        public static string S_PARAMETER_WINDOW {
            get {
                return ResourceManager.GetString("S_PARAMETER_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on windowed mode.
        /// </summary>
        public static string S_PARAMETER_WINDOW_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_WINDOW_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string S_PARAMETERS {
            get {
                return ResourceManager.GetString("S_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string S_PASSWORD {
            get {
                return ResourceManager.GetString("S_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string S_PLATFORM {
            get {
                return ResourceManager.GetString("S_PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 bits.
        /// </summary>
        public static string S_PLATFORM_32 {
            get {
                return ResourceManager.GetString("S_PLATFORM_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 bits.
        /// </summary>
        public static string S_PLATFORM_64 {
            get {
                return ResourceManager.GetString("S_PLATFORM_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (32).
        /// </summary>
        public static string S_PLATFORM_ANY {
            get {
                return ResourceManager.GetString("S_PLATFORM_ANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of ArmA 3 executable to launch.
        /// </summary>
        public static string S_PLATFORM_TIP {
            get {
                return ResourceManager.GetString("S_PLATFORM_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string S_PORT {
            get {
                return ResourceManager.GetString("S_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Warfare.
        /// </summary>
        public static string S_PRESET1 {
            get {
                return ResourceManager.GetString("S_PRESET1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Warfare [ALiVE].
        /// </summary>
        public static string S_PRESET2 {
            get {
                return ResourceManager.GetString("S_PRESET2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam [Unsung].
        /// </summary>
        public static string S_PRESET3 {
            get {
                return ResourceManager.GetString("S_PRESET3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        public static string S_PRIORITY {
            get {
                return ResourceManager.GetString("S_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above normal.
        /// </summary>
        public static string S_PRIORITY_ABOVENORMAL {
            get {
                return ResourceManager.GetString("S_PRIORITY_ABOVENORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string S_PRIORITY_HIGH {
            get {
                return ResourceManager.GetString("S_PRIORITY_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string S_PRIORITY_NORMAL {
            get {
                return ResourceManager.GetString("S_PRIORITY_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmA 3 process priority on Windows.
        /// </summary>
        public static string S_PRIORITY_TIP {
            get {
                return ResourceManager.GetString("S_PRIORITY_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string S_SERVER {
            get {
                return ResourceManager.GetString("S_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string S_SETTINGS_GENERAL {
            get {
                return ResourceManager.GetString("S_SETTINGS_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the application.
        /// </summary>
        public static string S_START_ACTION_CLOSE {
            get {
                return ResourceManager.GetString("S_START_ACTION_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the application.
        /// </summary>
        public static string S_START_ACTION_MINIMIZE {
            get {
                return ResourceManager.GetString("S_START_ACTION_MINIMIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string S_START_ACTION_NONE {
            get {
                return ResourceManager.GetString("S_START_ACTION_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string S_STATUS_READY {
            get {
                return ResourceManager.GetString("S_STATUS_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ArmA 3 version ({0}) doesn&apos;t match with the one on the 11th MEU servers ({1}).
        /// </summary>
        public static string S_VERSION_MISMATCH {
            get {
                return ResourceManager.GetString("S_VERSION_MISMATCH", resourceCulture);
            }
        }
    }
}
