//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11thLauncher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_11thLauncher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma3Sync is not configured, configure it in the settings window.
        /// </summary>
        public static string S_A3S_DISABLED_TIP {
            get {
                return ResourceManager.GetString("S_A3S_DISABLED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to launch Arma3Sync.
        /// </summary>
        public static string S_A3S_ENABLED_TIP {
            get {
                return ResourceManager.GetString("S_A3S_ENABLED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber.
        /// </summary>
        public static string S_ACCENT_AMBER {
            get {
                return ResourceManager.GetString("S_ACCENT_AMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string S_ACCENT_BLUE {
            get {
                return ResourceManager.GetString("S_ACCENT_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string S_ACCENT_BROWN {
            get {
                return ResourceManager.GetString("S_ACCENT_BROWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt.
        /// </summary>
        public static string S_ACCENT_COBALT {
            get {
                return ResourceManager.GetString("S_ACCENT_COBALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson.
        /// </summary>
        public static string S_ACCENT_CRIMSON {
            get {
                return ResourceManager.GetString("S_ACCENT_CRIMSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string S_ACCENT_CYAN {
            get {
                return ResourceManager.GetString("S_ACCENT_CYAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald.
        /// </summary>
        public static string S_ACCENT_EMERALD {
            get {
                return ResourceManager.GetString("S_ACCENT_EMERALD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string S_ACCENT_GREEN {
            get {
                return ResourceManager.GetString("S_ACCENT_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        public static string S_ACCENT_INDIGO {
            get {
                return ResourceManager.GetString("S_ACCENT_INDIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime.
        /// </summary>
        public static string S_ACCENT_LIME {
            get {
                return ResourceManager.GetString("S_ACCENT_LIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string S_ACCENT_MAGENTA {
            get {
                return ResourceManager.GetString("S_ACCENT_MAGENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauve.
        /// </summary>
        public static string S_ACCENT_MAUVE {
            get {
                return ResourceManager.GetString("S_ACCENT_MAUVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive.
        /// </summary>
        public static string S_ACCENT_OLIVE {
            get {
                return ResourceManager.GetString("S_ACCENT_OLIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string S_ACCENT_ORANGE {
            get {
                return ResourceManager.GetString("S_ACCENT_ORANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string S_ACCENT_PINK {
            get {
                return ResourceManager.GetString("S_ACCENT_PINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string S_ACCENT_PURPLE {
            get {
                return ResourceManager.GetString("S_ACCENT_PURPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string S_ACCENT_RED {
            get {
                return ResourceManager.GetString("S_ACCENT_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sienna.
        /// </summary>
        public static string S_ACCENT_SIENNA {
            get {
                return ResourceManager.GetString("S_ACCENT_SIENNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        public static string S_ACCENT_STEEL {
            get {
                return ResourceManager.GetString("S_ACCENT_STEEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taupe.
        /// </summary>
        public static string S_ACCENT_TAUPE {
            get {
                return ResourceManager.GetString("S_ACCENT_TAUPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        public static string S_ACCENT_TEAL {
            get {
                return ResourceManager.GetString("S_ACCENT_TEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        public static string S_ACCENT_VIOLET {
            get {
                return ResourceManager.GetString("S_ACCENT_VIOLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string S_ACCENT_YELLOW {
            get {
                return ResourceManager.GetString("S_ACCENT_YELLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking repository status.
        /// </summary>
        public static string S_ACTION_CHECK_REPOSITORY_STATUS {
            get {
                return ResourceManager.GetString("S_ACTION_CHECK_REPOSITORY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking server status.
        /// </summary>
        public static string S_ACTION_CHECK_SERVER_STATUS {
            get {
                return ResourceManager.GetString("S_ACTION_CHECK_SERVER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon presets.
        /// </summary>
        public static string S_ADDON_PRESETS {
            get {
                return ResourceManager.GetString("S_ADDON_PRESETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About 11th MEU Launcher.
        /// </summary>
        public static string S_APP_ABOUT {
            get {
                return ResourceManager.GetString("S_APP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11th MEU Launcher.
        /// </summary>
        public static string S_APP_NAME {
            get {
                return ResourceManager.GetString("S_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11th MEU Launcher Settings.
        /// </summary>
        public static string S_APP_SETTINGS {
            get {
                return ResourceManager.GetString("S_APP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma3Sync installation folder.
        /// </summary>
        public static string S_BROWSE_ARMA3SYNC_FOLDER {
            get {
                return ResourceManager.GetString("S_BROWSE_ARMA3SYNC_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma 3 game folder.
        /// </summary>
        public static string S_BROWSE_GAME_FOLDER {
            get {
                return ResourceManager.GetString("S_BROWSE_GAME_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Runtime Environment folder.
        /// </summary>
        public static string S_BROWSE_JAVA_FOLDER {
            get {
                return ResourceManager.GetString("S_BROWSE_JAVA_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string S_BTN_ABOUT {
            get {
                return ResourceManager.GetString("S_BTN_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the launcher.
        /// </summary>
        public static string S_BTN_ABOUT_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ABOUT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open addon website.
        /// </summary>
        public static string S_BTN_ADDON_LINK {
            get {
                return ResourceManager.GetString("S_BTN_ADDON_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected item down.
        /// </summary>
        public static string S_BTN_ADDONS_DOWN_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ADDONS_DOWN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected item up.
        /// </summary>
        public static string S_BTN_ADDONS_UP_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ADDONS_UP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string S_BTN_BROWSE {
            get {
                return ResourceManager.GetString("S_BTN_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse folder.
        /// </summary>
        public static string S_BTN_BROWSE_ADDON {
            get {
                return ResourceManager.GetString("S_BTN_BROWSE_ADDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check server status.
        /// </summary>
        public static string S_BTN_CHECK_SERVER_STATUS {
            get {
                return ResourceManager.GetString("S_BTN_CHECK_SERVER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to check server status.
        /// </summary>
        public static string S_BTN_CHECK_SERVER_STATUS_TIP {
            get {
                return ResourceManager.GetString("S_BTN_CHECK_SERVER_STATUS_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy launch shortcut to clipboard.
        /// </summary>
        public static string S_BTN_COPY_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("S_BTN_COPY_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new profile.
        /// </summary>
        public static string S_BTN_PROFILE_CREATE {
            get {
                return ResourceManager.GetString("S_BTN_PROFILE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        public static string S_BTN_PROFILE_DELETE {
            get {
                return ResourceManager.GetString("S_BTN_PROFILE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as favorite.
        /// </summary>
        public static string S_BTN_PROFILE_FAVORITE {
            get {
                return ResourceManager.GetString("S_BTN_PROFILE_FAVORITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated.
        /// </summary>
        public static string S_BTN_REPOSITORY_OUTDATED {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_OUTDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update to the repository. Click to check again.
        /// </summary>
        public static string S_BTN_REPOSITORY_OUTDATED_TIP {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_OUTDATED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string S_BTN_REPOSITORY_UNKNOWN {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to check the status of the repository.
        /// </summary>
        public static string S_BTN_REPOSITORY_UNKNOWN_TIP {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_UNKNOWN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string S_BTN_REPOSITORY_UPDATED {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version of the repository. Click to check again.
        /// </summary>
        public static string S_BTN_REPOSITORY_UPDATED_TIP {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_UPDATED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string S_BTN_RESET_SETTINGS {
            get {
                return ResourceManager.GetString("S_BTN_RESET_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string S_BTN_SETTINGS {
            get {
                return ResourceManager.GetString("S_BTN_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings window.
        /// </summary>
        public static string S_BTN_SETTINGS_TIP {
            get {
                return ResourceManager.GetString("S_BTN_SETTINGS_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle status.
        /// </summary>
        public static string S_BTN_TOGGLE_ADDON {
            get {
                return ResourceManager.GetString("S_BTN_TOGGLE_ADDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string S_BTN_UPDATE {
            get {
                return ResourceManager.GetString("S_BTN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string S_BTN_UPDATE_TIP {
            get {
                return ResourceManager.GetString("S_BTN_UPDATE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill server information.
        /// </summary>
        public static string S_BUTTON_FILL_SERVER_TIP {
            get {
                return ResourceManager.GetString("S_BUTTON_FILL_SERVER_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string S_BUTTON_SELECT_ALL_TIP {
            get {
                return ResourceManager.GetString("S_BUTTON_SELECT_ALL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select none.
        /// </summary>
        public static string S_BUTTON_SELECT_NONE_TIP {
            get {
                return ResourceManager.GetString("S_BUTTON_SELECT_NONE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check repository when the application starts (requires Java and Arma3Sync configured).
        /// </summary>
        public static string S_CHECKBOX_CHECK_REPOSITORY {
            get {
                return ResourceManager.GetString("S_CHECKBOX_CHECK_REPOSITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check servers status when the application starts.
        /// </summary>
        public static string S_CHECKBOX_CHECK_SERVERS {
            get {
                return ResourceManager.GetString("S_CHECKBOX_CHECK_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates when the application starts.
        /// </summary>
        public static string S_CHECKBOX_CHECK_UPDATES {
            get {
                return ResourceManager.GetString("S_CHECKBOX_CHECK_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string S_DEFAULT_PROFILE_NAME {
            get {
                return ResourceManager.GetString("S_DEFAULT_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmA 3.
        /// </summary>
        public static string S_GAME_NAME {
            get {
                return ResourceManager.GetString("S_GAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style: .
        /// </summary>
        public static string S_LABEL_ACCENT {
            get {
                return ResourceManager.GetString("S_LABEL_ACCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string S_LABEL_ADVANCED {
            get {
                return ResourceManager.GetString("S_LABEL_ADVANCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options.
        /// </summary>
        public static string S_LABEL_ADVANCED_SETTINGS {
            get {
                return ResourceManager.GetString("S_LABEL_ADVANCED_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by {0}.
        /// </summary>
        public static string S_LABEL_APP_AUTHOR {
            get {
                return ResourceManager.GetString("S_LABEL_APP_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma3Sync options.
        /// </summary>
        public static string S_LABEL_ARMA3SYNC_OPTIONS {
            get {
                return ResourceManager.GetString("S_LABEL_ARMA3SYNC_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma3Sync path:.
        /// </summary>
        public static string S_LABEL_ARMA3SYNC_PATH {
            get {
                return ResourceManager.GetString("S_LABEL_ARMA3SYNC_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build {0} [{1}] - {2}.
        /// </summary>
        public static string S_LABEL_BUILD {
            get {
                return ResourceManager.GetString("S_LABEL_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string S_LABEL_CANCEL {
            get {
                return ResourceManager.GetString("S_LABEL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game options.
        /// </summary>
        public static string S_LABEL_GAME_OPTIONS {
            get {
                return ResourceManager.GetString("S_LABEL_GAME_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmA 3 Path:.
        /// </summary>
        public static string S_LABEL_GAME_PATH {
            get {
                return ResourceManager.GetString("S_LABEL_GAME_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface options.
        /// </summary>
        public static string S_LABEL_INTERFACE_SETTINGS {
            get {
                return ResourceManager.GetString("S_LABEL_INTERFACE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected.
        /// </summary>
        public static string S_LABEL_JAVA_DETECTED {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCLAIMER: Only select Java path if it&apos;s not automatically detected on PATH or if you want to use a different version. Compatible JRE&apos;s: 7 and 8..
        /// </summary>
        public static string S_LABEL_JAVA_DISCLAIMER {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_DISCLAIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java options.
        /// </summary>
        public static string S_LABEL_JAVA_OPTIONS {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java path:.
        /// </summary>
        public static string S_LABEL_JAVA_PATH {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java in PATH:.
        /// </summary>
        public static string S_LABEL_JAVA_PATH_VAR {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_PATH_VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not detected.
        /// </summary>
        public static string S_LABEL_JAVA_UNDETECTED {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_UNDETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java has not been detected on PATH.
        /// </summary>
        public static string S_LABEL_JAVA_UNDETECTED_TIP {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_UNDETECTED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string S_LABEL_LANGUAGE {
            get {
                return ResourceManager.GetString("S_LABEL_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is distributed under GNU GPL v2 license. The program uses code from the following external libraries:.
        /// </summary>
        public static string S_LABEL_LICENSE {
            get {
                return ResourceManager.GetString("S_LABEL_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to notification area: .
        /// </summary>
        public static string S_LABEL_MINIMIZE_NOTIFICATION {
            get {
                return ResourceManager.GetString("S_LABEL_MINIMIZE_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string S_LABEL_NO {
            get {
                return ResourceManager.GetString("S_LABEL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string S_LABEL_OK {
            get {
                return ResourceManager.GetString("S_LABEL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of profiles.
        /// </summary>
        public static string S_LABEL_PROFILE_LIST {
            get {
                return ResourceManager.GetString("S_LABEL_PROFILE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string S_LABEL_PROFILE_NAME {
            get {
                return ResourceManager.GetString("S_LABEL_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string S_LABEL_REPOSITORIES {
            get {
                return ResourceManager.GetString("S_LABEL_REPOSITORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCLAIMER: This will delete all your parameters, settings and saved profiles..
        /// </summary>
        public static string S_LABEL_RESET_DISCLAIMER {
            get {
                return ResourceManager.GetString("S_LABEL_RESET_DISCLAIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete settings and profiles: .
        /// </summary>
        public static string S_LABEL_RESET_SETTINGS {
            get {
                return ResourceManager.GetString("S_LABEL_RESET_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save profile.
        /// </summary>
        public static string S_LABEL_SAVE_PROFILE {
            get {
                return ResourceManager.GetString("S_LABEL_SAVE_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string S_LABEL_SERVER {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map:.
        /// </summary>
        public static string S_LABEL_SERVER_MAP {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission:.
        /// </summary>
        public static string S_LABEL_SERVER_MISSION {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_MISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string S_LABEL_SERVER_NAME {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping:.
        /// </summary>
        public static string S_LABEL_SERVER_PING {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players:.
        /// </summary>
        public static string S_LABEL_SERVER_PLAYERS {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string S_LABEL_SERVER_VERSION {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After launching:.
        /// </summary>
        public static string S_LABEL_START_ACTION {
            get {
                return ResourceManager.GetString("S_LABEL_START_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup options.
        /// </summary>
        public static string S_LABEL_STARTUP_OPTIONS {
            get {
                return ResourceManager.GetString("S_LABEL_STARTUP_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme: .
        /// </summary>
        public static string S_LABEL_THEME {
            get {
                return ResourceManager.GetString("S_LABEL_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string S_LABEL_YES {
            get {
                return ResourceManager.GetString("S_LABEL_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join server.
        /// </summary>
        public static string S_LAUNCH_JOIN_SERVER {
            get {
                return ResourceManager.GetString("S_LAUNCH_JOIN_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ArmA 3.
        /// </summary>
        public static string S_LAUNCH_NORMAL {
            get {
                return ResourceManager.GetString("S_LAUNCH_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to restart the launcher to change language. Do you want to restart now?.
        /// </summary>
        public static string S_MSG_CHANGE_LANGUAGE_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_CHANGE_LANGUAGE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string S_MSG_CHANGE_LANGUAGE_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_CHANGE_LANGUAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder does not contain a valid Arma3Sync installation.
        /// </summary>
        public static string S_MSG_INCORRECT_ARMA3SYNC_PATH_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_ARMA3SYNC_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect path.
        /// </summary>
        public static string S_MSG_INCORRECT_ARMA3SYNC_PATH_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_ARMA3SYNC_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder does not contain a valid Java Runtime Environment (JRE).
        /// </summary>
        public static string S_MSG_INCORRECT_JAVA_PATH_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_JAVA_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect path.
        /// </summary>
        public static string S_MSG_INCORRECT_JAVA_PATH_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_JAVA_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder does not contain a valid Arma 3 installation.
        /// </summary>
        public static string S_MSG_INCORRECT_PATH_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect path.
        /// </summary>
        public static string S_MSG_INCORRECT_PATH_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The launcher has to be run with admin privileges to start ArmA 3..
        /// </summary>
        public static string S_MSG_LAUNCH_ERROR_CONTENT_ELEVATION {
            get {
                return ResourceManager.GetString("S_MSG_LAUNCH_ERROR_CONTENT_ELEVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The ArmA 3 executable path is not defined..
        /// </summary>
        public static string S_MSG_LAUNCH_ERROR_CONTENT_PATH {
            get {
                return ResourceManager.GetString("S_MSG_LAUNCH_ERROR_CONTENT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Steam has to be running to launch ArmA 3..
        /// </summary>
        public static string S_MSG_LAUNCH_ERROR_CONTENT_STEAM {
            get {
                return ResourceManager.GetString("S_MSG_LAUNCH_ERROR_CONTENT_STEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error launching ArmA 3. Check the application log for more details..
        /// </summary>
        public static string S_MSG_LAUNCH_ERROR_CONTENT_UNKNOWN {
            get {
                return ResourceManager.GetString("S_MSG_LAUNCH_ERROR_CONTENT_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch game.
        /// </summary>
        public static string S_MSG_LAUNCH_ERROR_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_LAUNCH_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest available version of the program.
        /// </summary>
        public static string S_MSG_NO_UPDATES_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_NO_UPDATES_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        public static string S_MSG_NO_UPDATES_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_NO_UPDATES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string S_MSG_OPTION_NO {
            get {
                return ResourceManager.GetString("S_MSG_OPTION_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string S_MSG_OPTION_YES {
            get {
                return ResourceManager.GetString("S_MSG_OPTION_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution path has not been auto-detected, select it manually on the settings window before using the application.
        /// </summary>
        public static string S_MSG_PATH_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution path.
        /// </summary>
        public static string S_MSG_PATH_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all the data and existing profiles?.
        /// </summary>
        public static string S_MSG_RESET_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_RESET_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string S_MSG_RESET_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_RESET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update available. Do you want to update now?.
        /// </summary>
        public static string S_MSG_UPDATE_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error checking updates. Try again later.
        /// </summary>
        public static string S_MSG_UPDATE_ERROR_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_ERROR_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string S_MSG_UPDATE_ERROR_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error updating the application, try again later.
        /// </summary>
        public static string S_MSG_UPDATE_FAIL_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_FAIL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating.
        /// </summary>
        public static string S_MSG_UPDATE_FAIL_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_FAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been updated successfully.
        /// </summary>
        public static string S_MSG_UPDATE_SUCCESS_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_SUCCESS_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application updated.
        /// </summary>
        public static string S_MSG_UPDATE_SUCCESS_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_SUCCESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string S_MSG_UPDATE_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile name.
        /// </summary>
        public static string S_NEW_PROFILE_NAME {
            get {
                return ResourceManager.GetString("S_NEW_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional parameters.
        /// </summary>
        public static string S_PARAMETER_ADDITIONAL {
            get {
                return ResourceManager.GetString("S_PARAMETER_ADDITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other parameters to use.
        /// </summary>
        public static string S_PARAMETER_ADDITIONAL_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_ADDITIONAL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line parameter.
        /// </summary>
        public static string S_PARAMETER_COMMAND {
            get {
                return ResourceManager.GetString("S_PARAMETER_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Count.
        /// </summary>
        public static string S_PARAMETER_CPU_COUNT {
            get {
                return ResourceManager.GetString("S_PARAMETER_CPU_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of CPU cores to use (equal or less than the number of processor cores).
        /// </summary>
        public static string S_PARAMETER_CPU_COUNT_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_CPU_COUNT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty world.
        /// </summary>
        public static string S_PARAMETER_EMPTY_WORLD {
            get {
                return ResourceManager.GetString("S_PARAMETER_EMPTY_WORLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t load any world by default.
        /// </summary>
        public static string S_PARAMETER_EMPTY_WORLD_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_EMPTY_WORLD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of additional threads to use.
        /// </summary>
        public static string S_PARAMETER_EX_THREADS_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_EX_THREADS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra threads.
        /// </summary>
        public static string S_PARAMETER_EXTHREADS {
            get {
                return ResourceManager.GetString("S_PARAMETER_EXTHREADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable file patching.
        /// </summary>
        public static string S_PARAMETER_FILE_PATCHING {
            get {
                return ResourceManager.GetString("S_PARAMETER_FILE_PATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows loading of unpacked data.
        /// </summary>
        public static string S_PARAMETER_FILE_PATCHING_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_FILE_PATCHING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for hugepages on memory.
        /// </summary>
        public static string S_PARAMETER_HUGE_PAGES {
            get {
                return ResourceManager.GetString("S_PARAMETER_HUGE_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables hugepages support on memory.
        /// </summary>
        public static string S_PARAMETER_HUGE_PAGES_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_HUGE_PAGES_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Hyper-Threading.
        /// </summary>
        public static string S_PARAMETER_HYPERTHREADING {
            get {
                return ResourceManager.GetString("S_PARAMETER_HYPERTHREADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the use of CPU cores with Hyper-Threading.
        /// </summary>
        public static string S_PARAMETER_HYPERTHREADING_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_HYPERTHREADING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocator - 32-bit.
        /// </summary>
        public static string S_PARAMETER_MALLOC_32 {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select memory allocator to use.
        /// </summary>
        public static string S_PARAMETER_MALLOC_32_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_32_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocator - 64-bit.
        /// </summary>
        public static string S_PARAMETER_MALLOC_64 {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select memory allocator to use.
        /// </summary>
        public static string S_PARAMETER_MALLOC_64_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_64_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System (Windows).
        /// </summary>
        public static string S_PARAMETER_MALLOC_SYSTEM {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM memory limit.
        /// </summary>
        public static string S_PARAMETER_MAX_MEMORY {
            get {
                return ResourceManager.GetString("S_PARAMETER_MAX_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of RAM memory available.
        /// </summary>
        public static string S_PARAMETER_MAX_MEMORY_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MAX_MEMORY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video memory limit.
        /// </summary>
        public static string S_PARAMETER_MAX_VMEMORY {
            get {
                return ResourceManager.GetString("S_PARAMETER_MAX_VMEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of video memory available.
        /// </summary>
        public static string S_PARAMETER_MAX_VMEMORY_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MAX_VMEMORY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs.
        /// </summary>
        public static string S_PARAMETER_NO_LOGS {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save errors to the RPT log.
        /// </summary>
        public static string S_PARAMETER_NO_LOGS_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_LOGS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off multicore.
        /// </summary>
        public static string S_PARAMETER_NO_MULTICORE {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_MULTICORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the use of multiple cores.
        /// </summary>
        public static string S_PARAMETER_NO_MULTICORE_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_MULTICORE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pause.
        /// </summary>
        public static string S_PARAMETER_NO_PAUSE {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to continue running the game when the window is not active.
        /// </summary>
        public static string S_PARAMETER_NO_PAUSE_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_PAUSE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable splash screens.
        /// </summary>
        public static string S_PARAMETER_NO_SPLASH {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_SPLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the splash screens on load.
        /// </summary>
        public static string S_PARAMETER_NO_SPLASH_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_SPLASH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show script errors.
        /// </summary>
        public static string S_PARAMETER_SHOW_ERRORS {
            get {
                return ResourceManager.GetString("S_PARAMETER_SHOW_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show script errors on screen.
        /// </summary>
        public static string S_PARAMETER_SHOW_ERRORS_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_SHOW_ERRORS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static screen on main menu.
        /// </summary>
        public static string S_PARAMETER_SKIP_INTRO {
            get {
                return ResourceManager.GetString("S_PARAMETER_SKIP_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the scene on the main menu.
        /// </summary>
        public static string S_PARAMETER_SKIP_INTRO_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_SKIP_INTRO_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force windowed mode.
        /// </summary>
        public static string S_PARAMETER_WINDOW {
            get {
                return ResourceManager.GetString("S_PARAMETER_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on windowed mode.
        /// </summary>
        public static string S_PARAMETER_WINDOW_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_WINDOW_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string S_PARAMETERS {
            get {
                return ResourceManager.GetString("S_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string S_PASSWORD {
            get {
                return ResourceManager.GetString("S_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string S_PLATFORM {
            get {
                return ResourceManager.GetString("S_PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 bits.
        /// </summary>
        public static string S_PLATFORM_32 {
            get {
                return ResourceManager.GetString("S_PLATFORM_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 bits.
        /// </summary>
        public static string S_PLATFORM_64 {
            get {
                return ResourceManager.GetString("S_PLATFORM_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of ArmA 3 executable to launch.
        /// </summary>
        public static string S_PLATFORM_TIP {
            get {
                return ResourceManager.GetString("S_PLATFORM_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string S_PORT {
            get {
                return ResourceManager.GetString("S_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        public static string S_PRIORITY {
            get {
                return ResourceManager.GetString("S_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above normal.
        /// </summary>
        public static string S_PRIORITY_ABOVENORMAL {
            get {
                return ResourceManager.GetString("S_PRIORITY_ABOVENORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string S_PRIORITY_HIGH {
            get {
                return ResourceManager.GetString("S_PRIORITY_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string S_PRIORITY_NORMAL {
            get {
                return ResourceManager.GetString("S_PRIORITY_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmA 3 process priority on Windows.
        /// </summary>
        public static string S_PRIORITY_TIP {
            get {
                return ResourceManager.GetString("S_PRIORITY_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string S_PROFILES {
            get {
                return ResourceManager.GetString("S_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string S_SERVER {
            get {
                return ResourceManager.GetString("S_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string S_SERVERS {
            get {
                return ResourceManager.GetString("S_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string S_SETTINGS_GENERAL {
            get {
                return ResourceManager.GetString("S_SETTINGS_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string S_SETTINGS_INTERFACE {
            get {
                return ResourceManager.GetString("S_SETTINGS_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string S_SETTINGS_REPOSITORY {
            get {
                return ResourceManager.GetString("S_SETTINGS_REPOSITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the application.
        /// </summary>
        public static string S_START_ACTION_CLOSE {
            get {
                return ResourceManager.GetString("S_START_ACTION_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the application.
        /// </summary>
        public static string S_START_ACTION_MINIMIZE {
            get {
                return ResourceManager.GetString("S_START_ACTION_MINIMIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string S_START_ACTION_NONE {
            get {
                return ResourceManager.GetString("S_START_ACTION_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string S_STATUS_READY {
            get {
                return ResourceManager.GetString("S_STATUS_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string S_THEME_DARK {
            get {
                return ResourceManager.GetString("S_THEME_DARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string S_THEME_LIGHT {
            get {
                return ResourceManager.GetString("S_THEME_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ArmA 3 version ({0}) doesn&apos;t match with one or more servers ({1}).
        /// </summary>
        public static string S_VERSION_MISMATCH {
            get {
                return ResourceManager.GetString("S_VERSION_MISMATCH", resourceCulture);
            }
        }
    }
}
