//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11thLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_11thLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _11thLauncherUpdater {
            get {
                object obj = ResourceManager.GetObject("_11thLauncherUpdater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap a3sDisabled {
            get {
                object obj = ResourceManager.GetObject("a3sDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] A3SDS {
            get {
                object obj = ResourceManager.GetObject("A3SDS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap a3sEnabled {
            get {
                object obj = ResourceManager.GetObject("a3sEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap menu_settings {
            get {
                object obj = ResourceManager.GetObject("menu_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap off {
            get {
                object obj = ResourceManager.GetObject("off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap on {
            get {
                object obj = ResourceManager.GetObject("on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets de addons.
        /// </summary>
        public static string S_ADDON_PRESETS {
            get {
                return ResourceManager.GetString("S_ADDON_PRESETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11th MEU Launcher.
        /// </summary>
        public static string S_APP_NAME {
            get {
                return ResourceManager.GetString("S_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mover abajo seleccionado.
        /// </summary>
        public static string S_BTN_ADDONS_DOWN_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ADDONS_DOWN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mover arriba seleccionado.
        /// </summary>
        public static string S_BTN_ADDONS_UP_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ADDONS_UP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predeterminado.
        /// </summary>
        public static string S_DEFAULT_PROFILE_NAME {
            get {
                return ResourceManager.GetString("S_DEFAULT_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmA 3.
        /// </summary>
        public static string S_GAME_NAME {
            get {
                return ResourceManager.GetString("S_GAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectar al servidor.
        /// </summary>
        public static string S_LAUNCH_JOIN_SERVER {
            get {
                return ResourceManager.GetString("S_LAUNCH_JOIN_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar ArmA 3.
        /// </summary>
        public static string S_LAUNCH_NORMAL {
            get {
                return ResourceManager.GetString("S_LAUNCH_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario ejecutar el launcher con permisos de administrador para lanzar el juego.
        /// </summary>
        public static string S_MSG_ELEVATION_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_ELEVATION_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisos de administrador.
        /// </summary>
        public static string S_MSG_ELEVATION_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_ELEVATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción global no controlada.
        /// </summary>
        public static string S_MSG_GENERIC_DOMAIN_EXCEPTION {
            get {
                return ResourceManager.GetString("S_MSG_GENERIC_DOMAIN_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción no controlada.
        /// </summary>
        public static string S_MSG_GENERIC_EXCEPTION {
            get {
                return ResourceManager.GetString("S_MSG_GENERIC_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario que Steam esté en ejecución para lanzar el juego.
        /// </summary>
        public static string S_MSG_NO_STEAM_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_NO_STEAM_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam no detectado.
        /// </summary>
        public static string S_MSG_NO_STEAM_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_NO_STEAM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta de ejecución no ha sido autodetectada, indicala manualmente en la ventana de opciones antes de empezar a utilizar la aplicación.
        /// </summary>
        public static string S_MSG_PATH_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de ejecución.
        /// </summary>
        public static string S_MSG_PATH_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros adicionales.
        /// </summary>
        public static string S_PARAMETER_ADDITIONAL {
            get {
                return ResourceManager.GetString("S_PARAMETER_ADDITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros parámetros a utilizar.
        /// </summary>
        public static string S_PARAMETER_ADDITIONAL_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_ADDITIONAL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametro de linea de comandos.
        /// </summary>
        public static string S_PARAMETER_COMMAND {
            get {
                return ResourceManager.GetString("S_PARAMETER_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mundo vacío.
        /// </summary>
        public static string S_PARAMETER_EMPTY_WORLD {
            get {
                return ResourceManager.GetString("S_PARAMETER_EMPTY_WORLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cargar ningún mapa por defecto.
        /// </summary>
        public static string S_PARAMETER_EMPTY_WORLD_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_EMPTY_WORLD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar parcheo de archivos.
        /// </summary>
        public static string S_PARAMETER_FILE_PATCHING {
            get {
                return ResourceManager.GetString("S_PARAMETER_FILE_PATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite cargar datos no empaquetados.
        /// </summary>
        public static string S_PARAMETER_FILE_PATCHING_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_FILE_PATCHING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soporte para páginas grandes.
        /// </summary>
        public static string S_PARAMETER_HUGE_PAGES {
            get {
                return ResourceManager.GetString("S_PARAMETER_HUGE_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa el soporte para páginas grandes en la memoria.
        /// </summary>
        public static string S_PARAMETER_HUGE_PAGES_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_HUGE_PAGES_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar Hyper-Threading.
        /// </summary>
        public static string S_PARAMETER_HYPERTHREADING {
            get {
                return ResourceManager.GetString("S_PARAMETER_HYPERTHREADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa la utilización de núcleos de CPU con Hyper-Threading.
        /// </summary>
        public static string S_PARAMETER_HYPERTHREADING_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_HYPERTHREADING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignador de memoria - 32-bit.
        /// </summary>
        public static string S_PARAMETER_MALLOC_32 {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el asignador de memoria a utilizar.
        /// </summary>
        public static string S_PARAMETER_MALLOC_32_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_32_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignador de memoria - 64-bit.
        /// </summary>
        public static string S_PARAMETER_MALLOC_64 {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el asignador de memoria a utilizar.
        /// </summary>
        public static string S_PARAMETER_MALLOC_64_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_64_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema (Windows).
        /// </summary>
        public static string S_PARAMETER_MALLOC_SYSTEM {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs.
        /// </summary>
        public static string S_PARAMETER_NO_LOGS {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No guardar errores al log .RPT.
        /// </summary>
        public static string S_PARAMETER_NO_LOGS_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_LOGS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar multinúcleo.
        /// </summary>
        public static string S_PARAMETER_NO_MULTICORE {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_MULTICORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactiva el uso de múltiples núcleos.
        /// </summary>
        public static string S_PARAMETER_NO_MULTICORE_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_MULTICORE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pausar.
        /// </summary>
        public static string S_PARAMETER_NO_PAUSE {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite seguir ejecutando el juego incluso cuando la ventana no está activa.
        /// </summary>
        public static string S_PARAMETER_NO_PAUSE_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_PAUSE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar logos al iniciar.
        /// </summary>
        public static string S_PARAMETER_NO_SPLASH {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_SPLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactiva las pantallas de inicio.
        /// </summary>
        public static string S_PARAMETER_NO_SPLASH_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_SPLASH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar errores de script.
        /// </summary>
        public static string S_PARAMETER_SHOW_ERRORS {
            get {
                return ResourceManager.GetString("S_PARAMETER_SHOW_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra los errores de scripts en pantalla.
        /// </summary>
        public static string S_PARAMETER_SHOW_ERRORS_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_SHOW_ERRORS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondo estático en menú.
        /// </summary>
        public static string S_PARAMETER_SKIP_INTRO {
            get {
                return ResourceManager.GetString("S_PARAMETER_SKIP_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactiva la escena en el menú principal.
        /// </summary>
        public static string S_PARAMETER_SKIP_INTRO_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_SKIP_INTRO_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forzar modo ventana.
        /// </summary>
        public static string S_PARAMETER_WINDOW {
            get {
                return ResourceManager.GetString("S_PARAMETER_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecuta el juego en modo ventana.
        /// </summary>
        public static string S_PARAMETER_WINDOW_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_WINDOW_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros.
        /// </summary>
        public static string S_PARAMETERS {
            get {
                return ResourceManager.GetString("S_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string S_PASSWORD {
            get {
                return ResourceManager.GetString("S_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataforma:.
        /// </summary>
        public static string S_PLATFORM {
            get {
                return ResourceManager.GetString("S_PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 bits.
        /// </summary>
        public static string S_PLATFORM_32 {
            get {
                return ResourceManager.GetString("S_PLATFORM_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 bits.
        /// </summary>
        public static string S_PLATFORM_64 {
            get {
                return ResourceManager.GetString("S_PLATFORM_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por defecto (32).
        /// </summary>
        public static string S_PLATFORM_ANY {
            get {
                return ResourceManager.GetString("S_PLATFORM_ANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de ejecutable de ArmA 3 a lanzar.
        /// </summary>
        public static string S_PLATFORM_TIP {
            get {
                return ResourceManager.GetString("S_PLATFORM_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto.
        /// </summary>
        public static string S_PORT {
            get {
                return ResourceManager.GetString("S_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guerra Moderna.
        /// </summary>
        public static string S_PRESET1 {
            get {
                return ResourceManager.GetString("S_PRESET1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guerra Moderna [ALiVE].
        /// </summary>
        public static string S_PRESET2 {
            get {
                return ResourceManager.GetString("S_PRESET2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam [Unsung].
        /// </summary>
        public static string S_PRESET3 {
            get {
                return ResourceManager.GetString("S_PRESET3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioridad:.
        /// </summary>
        public static string S_PRIORITY {
            get {
                return ResourceManager.GetString("S_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encima de lo normal.
        /// </summary>
        public static string S_PRIORITY_ABOVENORMAL {
            get {
                return ResourceManager.GetString("S_PRIORITY_ABOVENORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta.
        /// </summary>
        public static string S_PRIORITY_HIGH {
            get {
                return ResourceManager.GetString("S_PRIORITY_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string S_PRIORITY_NORMAL {
            get {
                return ResourceManager.GetString("S_PRIORITY_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioridad del proceso de ArmA 3 en Windows.
        /// </summary>
        public static string S_PRIORITY_TIP {
            get {
                return ResourceManager.GetString("S_PRIORITY_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor.
        /// </summary>
        public static string S_SERVER {
            get {
                return ResourceManager.GetString("S_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo.
        /// </summary>
        public static string S_STATUS_READY {
            get {
                return ResourceManager.GetString("S_STATUS_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam no está en ejecución. Es necesario tener abierto Steam para lanzar ArmA 3.
        /// </summary>
        public static string S_STEAM_OFF {
            get {
                return ResourceManager.GetString("S_STEAM_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu versión de ArmA 3 ({0}) no concuerda con la de los servidores de la 11th MEU ({1}).
        /// </summary>
        public static string S_VERSION_MISMATCH {
            get {
                return ResourceManager.GetString("S_VERSION_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
